version: '3.9'

services:

  mysql:
    container_name: mysql-tc
    image: mysql:8.4.0
    hostname: docker-mysql
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}"
    volumes:
      - mysql_db:/var/lib/mysql:delegated
      - ./volumes/etc/mysql/conf.d:/etc/mysql/conf.d:cached
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - internal

  teamcity:
    container_name: teamcity-tc
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    ports:
      - "${TEAMCITY_HOST_PORT}:${TEAMCITY_CONTAINER_PORT}"
    volumes:
      - ./volumes/data/teamcity_server/datadir:/data/teamcity_server/datadir
      - ./volumes/opt/teamcity/logs:/opt/teamcity/logs
    depends_on:
      - mysql
    networks:
      - internal

  teamcity-agent-1:
    container_name: teamcity-agent-1-tc
    build:
      context: ./images/teamcity_agent
      args:
        TEAMCITY_VERSION: ${TEAMCITY_VERSION}
    privileged: true
    volumes:
      - ./volumes/data/teamcity_agent/conf/agent1:/data/teamcity_agent/conf
      - ./volumes/home/buildagent/.ssh:/home/buildagent/.ssh
      - ./volumes/opt/buildagent_1/logs:/opt/buildagent/logs
    environment:
      - DOCKER_IN_DOCKER=start
    depends_on:
      - teamcity
    networks:
      - internal

  teamcity-agent-2:
    container_name: teamcity-agent-2-tc
    build:
      context: ./images/teamcity_agent
      args:
        TEAMCITY_VERSION: ${TEAMCITY_VERSION}
    privileged: true
    volumes:
      - ./volumes/data/teamcity_agent/conf/agent2:/data/teamcity_agent/conf
      - ./volumes/home/buildagent/.ssh:/home/buildagent/.ssh
      - ./volumes/opt/buildagent_2/logs:/opt/buildagent/logs
    environment:
      - DOCKER_IN_DOCKER=start
    depends_on:
      - teamcity
    networks:
      - internal

  teamcity-agent-3:
    container_name: teamcity-agent-3-tc
    build:
      context: ./images/teamcity_agent
      args:
        TEAMCITY_VERSION: ${TEAMCITY_VERSION}
    privileged: true
    volumes:
      - ./volumes/data/teamcity_agent/conf/agent3:/data/teamcity_agent/conf
      - ./volumes/home/buildagent/.ssh:/home/buildagent/.ssh
      - ./volumes/opt/buildagent_3/logs:/opt/buildagent/logs
    environment:
      - DOCKER_IN_DOCKER=start
    depends_on:
      - teamcity
    networks:
      - internal

volumes:

  mysql_db:
    driver: local
    driver_opts:
      type: none
      device: $PWD/volumes/var/lib/mysql
      o: bind

networks:

  internal:
    driver: bridge